### ISSUE TITLE
trying to fix my broken docs

### ISSUE THREAD

**Issue by kklmn** [readthedocs/sphinx-build-compatibility#1]
Hello,

[My docs](https://xrt.readthedocs.io/) are now broken as a result of the recent (re)(e)volution of readthedocs.io and I don't really know what to do.

First, your motivation looks upside down: "... making a Sphinx project to build exactly in the same way that it would build locally". This is what I used to have. The same build was done locally and on rtfd.io. And now it is not.

Second, the suggested fix doesn't work. That chunk of code from [here](https://about.readthedocs.com/blog/2024/07/addons-by-default/#how-does-it-affect-my-projects) does nothing and `sphinx-build-compatibility` fails with 
```
Running Sphinx v7.2.6
Running "manipulate_config" from Read the Docs "sphinx_build_compatibility" extension. Consider removing it from your requirements and migrating your documentation accordingly. This extension is useful only as a transition but it will not be maintained.

Extension error (sphinx_build_compatibility.extension):
Handler <function manipulate_config at 0x0000028F5149BC40> for event 'config-inited' threw an exception (exception: argument of type 'NoneType' is not iterable)
```
What is this Sphinx extension supposed to do? And how to make it work?

Thank you very much!

**Comment by humitos** [comment]
> My docs are now broken

Broken, how? What's the error you are receiving? Can you link the URL of the failing build?

**Comment by kklmn** [comment]
The builds did work, but the final html view was broken. The locations of _static and images have changed. I have adapted my conf.py and my sphinx extension to this. Now it looks good again.
